issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:cert-manager/webhook-cert-lib:ref:refs/heads/(main|master)$

permissions:
  administration: read
  contents: write
  issues: write
  pull_requests: write
  security_events: read
  statuses: write
  workflows: write
